Universe  = vanilla
Executable = /bin/sh
Arguments  = /sphenix/user/dcxchenxi/develope/macros/TrackingProduction/run_kshort_reco.sh $(Process) 0
Notify_user = 997873828mcx@gmail.com

# Log file paths
Output  = /sphenix/user/dcxchenxi/develope/macros/TrackingProduction/log/kshort_reco_next_$(Process).out
Error   = /sphenix/user/dcxchenxi/develope/macros/TrackingProduction/log/kshort_reco_next_$(Process).err
Log     = /sphenix/user/dcxchenxi/develope/macros/TrackingProduction/log/tmp/kshort_reco_next_$(Process).log

# Working directory
Initialdir = /sphenix/user/dcxchenxi/develope/macros/TrackingProduction/

# Resource requests (adjust based on your job needs)
RequestMemory = 20000
RequestDisk = 20000
# RequestCpus = 1  # Uncomment if you need multiple CPUs

# Job management
PeriodicHold = (NumJobStarts>=2 && JobStatus == 1)
# Notification settings
Notification = Error

#Queue 11
Queue 2628