#ifndef MACRO_GENERATEPYTHIA8HEPMC_C
#define MACRO_GENERATEPYTHIA8HEPMC_C

#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllServer.h>

#include <phhepmc/Fun4AllHepMCOutputManager.h>

#include <phpythia8/PHPythia8.h>

#include <phool/PHRandomSeed.h>
#include <phool/recoConsts.h>

#include <Rtypes.h>
#include <TSystem.h>

#include <cstdlib>
#include <iostream>
#include <string>

R__LOAD_LIBRARY(libfun4all.so)
R__LOAD_LIBRARY(libphhepmc.so)
R__LOAD_LIBRARY(libPHPythia8.so)

int GeneratePythia8HepMC(
    const int nEvents = 1000,
    const std::string &outputFile = "output/pp_minbias_pythia8.hepmc",
    const std::string &configFile = "",
    const int randomSeed = 0,
    const int verbosity = 0)
{
  if (nEvents <= 0)
  {
    std::cout << "GeneratePythia8HepMC - nEvents must be positive" << std::endl;
    return 1;
  }

  std::string cfg = configFile;
  if (cfg.empty())
  {
    const char *calibrationroot = gSystem->Getenv("CALIBRATIONROOT");
    if (!calibrationroot)
    {
      std::cout << "GeneratePythia8HepMC - CALIBRATIONROOT is not set. "
                << "Run sphenix_setup.sh first or pass configFile explicitly." << std::endl;
      return 1;
    }
    cfg = std::string(calibrationroot) + "/Generators/phpythia8_detroit_minBias.cfg";
  }

  const auto slash = outputFile.find_last_of('/');
  if (slash != std::string::npos)
  {
    const std::string outdir = outputFile.substr(0, slash);
    if (!outdir.empty())
    {
      gSystem->mkdir(outdir.c_str(), true);
    }
  }

  Fun4AllServer *se = Fun4AllServer::instance();
  se->Verbosity(verbosity);

  PHRandomSeed::Verbosity(1);
  recoConsts *rc = recoConsts::instance();
  if (randomSeed > 0)
  {
    rc->set_IntFlag("RANDOMSEED", randomSeed);
  }

  auto *pythia8 = new PHPythia8("PHPythia8_pp_minbias");
  pythia8->Verbosity(verbosity);
  pythia8->set_config_file(cfg);
  pythia8->set_embedding_id(1);
  pythia8->save_integrated_luminosity(false);
  se->registerSubsystem(pythia8);

  auto *hepmcOut = new Fun4AllHepMCOutputManager("HEPMCOUT", outputFile);
  hepmcOut->set_embedding_id(1);
  hepmcOut->AddComment("sPHENIX pp Pythia8 minbias HepMC generated by GeneratePythia8HepMC.C");
  se->registerOutputManager(hepmcOut);

  auto *in = new Fun4AllDummyInputManager("DUMMY");
  in->Verbosity(verbosity);
  se->registerInputManager(in);

  std::cout << "GeneratePythia8HepMC - config: " << cfg << std::endl;
  std::cout << "GeneratePythia8HepMC - output: " << outputFile << std::endl;
  std::cout << "GeneratePythia8HepMC - events: " << nEvents << std::endl;

  se->run(nEvents);
  se->End();

  delete se;
  gSystem->Exit(0);
  return 0;
}

#endif
